---
title: "wind_analysis"
author: "Steven Cognac"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dataRetrieval) 
library(tidyverse)
library(here)
library(patchwork)
library(readr)
library(feasts)
#library(smooth)
#library(slider)
library(lubridate)
library(tibbletime)
```

Data downloaded from the NOAA National Centers for Environmental Information (NCEI) Climate Data Online search tool for Local Climatological Data (LCD) - (https://www.ncdc.noaa.gov/cdo-web/datatools/lcd)

https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc:C00684/html

10-year Date Range
Start:	2011-10-01
End: 	2021-09-30

Stations
 - VACAVILLE NUT TREE AIRPORT ASOS, CA US (Station No: WBAN:93241)
 - SACRAMENTO AIRPORT ASOS, CA US (Station No: WBAN:23232)
 - CONCORD BUCHANAN FIELD, CA US (WBAN:23254)


sacramento airport metadata - https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USW00023232/detail

```{r}
wind_vaca_raw <- read_csv(here("data", "2805190_vacaville.csv")) %>%
  as_tsibble(index = DATE, key = HourlyWindSpeed)
```


```{r}
wind_vaca_raw <- read_csv(here("data", "2805190_vacaville.csv")) %>% 
  select(2,56:58) %>% 
  filter(DATE > "2014-12-31 23:59:00") %>% 
  as_tbl_time(index = DATE) %>% 
  mutate(station = "vacaville")

wind_sac_raw <- read_csv(here("data", "2805192_sacramento.csv")) %>% 
  select(2,56:58) %>% 
  filter(DATE > "2014-12-31 23:59:00") %>% 
  as_tbl_time(index = DATE) %>% 
  mutate(station = "sacramento_airport")

wind_concord_raw <- read_csv(here("data", "2805195_concord.csv")) %>% 
  select(2,56:58) %>% 
  filter(DATE > "2014-12-31 23:59:00") %>% 
  as_tbl_time(index = DATE) %>% 
  mutate(station = "concord")

wind_raw <- rbind(wind_vaca_raw, wind_sac_raw, wind_concord_raw)

# mutate(DATE = as_datetime(DATE,"%Y-%m-%d %H:%M:%s"))

```

```{r}
wind_vaca_raw
```


```{r}
class(wind_vaca_raw)
lapply(wind_vaca_raw, class)
```

https://blog.earo.me/2018/02/06/tsibble-or-tibbletime/

```{r}
#set time interval.  Can be by day, month, hour, year, etc.
interval = "2 hours"

wind <- wind_raw %>% 
  group_by(station) %>% 
  collapse_by(period = interval) %>% 
  group_by(DATE, station) %>% 
  summarise(
    wind_avg = mean(HourlyWindSpeed, na.rm = TRUE)
  )

ggplot(wind, aes(x = DATE, y = wind_avg, color = station)) +
  geom_line()
```

```{r}
# calculate 5-day moving average
# wind is hourly

wind_decomp <- wind_raw %>% 
  as_tsibble() %>% 
  select(DATE, HourlyWindSpeed) %>% 
  model(decomposition_model(HourlyWindSpeed, type = "additive")) %>% 
  components() %>% 
  autoplot()


```
```{r}
vaca <- wind_vaca_raw %>% 
  mutate(ma = slider::slide_dbl(HourlyWindSpeed, mean,
                .before = 2, .after = 2, .complete = TRUE))

ggplot(data = vaca, aes(x = DATE, y = HourlyWindSpeed)) +
  geom_line() +
  geom_smooth(show.legend = TRUE)
```


```{r}
plot.ts(wind_concord_raw$HourlyWindSpeed)
plot.ts(wind_sac_raw$HourlyWindSpeed)
plot.ts(wind_vaca_raw$HourlyWindSpeed)
```


```{r}
ggplot(data = wind_vaca_raw, aes(x = DATE, y = HourlyWindSpeed)) +
  geom_line() +
  geom_smooth(show.legend = TRUE)

```
```{r}
wind_filt <- wind_raw %>% 
  select(DATE, HourlyWindSpeed)

decomp <- as_tsibble(wind_filt) %>% 
  model(classical_decomposition(HourlyWindSpeed, type = 'additive')) %>% 
  components()

autoplot(decomp) +
  labs(title = "Average Wind Speed at Travis Air Force Base, Solano County, California",
       subtitle = "Classical Decomposition: HourlyWindSpeed = trend + seasonal + random")
decomp
```

